[package]
name = "glshader-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
gstreamer = "0.20.3"
gstreamer-gl = "0.20.0"
glib = { version = "0.17", default_features = false }
